### PR TITLE
Add parameter count adjustment for functions that are class methods

### PR DESCRIPTION
**Pull request by richmr**
Hi, I am using PyGAD.GA inside of another class.  The various functions PyGAD will accept as parameters have strict parameter count checks.  However, when you assign a class method to these functions they get an extra "self" parameter assigned to them.  PyGAD then interprets these extra self parameters as improperly constructed functions.

Using the "inspect" module I have added a check to see if an assigned function is actually a method.  If so, it then adds one to the expected parameter count.  This allows these methods to be used as contributing functions.  This, in turn, permits more well-formatted object oriented code to be used when desired.  Users can still assign non-class functions to these parameters and the code will accept them.

I am using this in my current experiments and it is working well.

Thanks for your time!

Mike

### CODE REVIEW

**Comment by mschrader15** [comment]
Bumping this. Would be really nice to have!

**Comment by richmr** [comment]
It does prevent PyGAD "save" function from working due to pickle issue, I discovered after submission.  I did not correct that issue since I don't use "save".  I see jack89roberts comment but I am not having any issues with a wide variety of fitness functions myself.

**Comment by mschrader15** [comment]
We built a hacky solution for >2 arguments by saving the other arguments to a common temporary file and using a closure for the time being, but the class based method is ultimately what we want. I'll fork from your branch from the time being!

**Comment by richmr** [comment]
Good luck!  Just be aware my fork is not up to date with the main.  The new
keep_elitism function is not in my code.  I probably need to do something
about that.

Mike

**Comment by ahmedfgad** [comment]
Thanks @richmr. This is a useful feature.

**Comment by richmr** [comment]
Woohoo!

**Comment by whubaichuan** [comment]
@ahmedfgad hi, could you please share a code example for the 4th update in Pygad 2.19.0 Release? Is there any relationship to the class instance or class method? I am confused about this function but I am interested.

**Comment by richmr** [comment]
If you are referring to this pull, all that was added was the ability to use class methods ("def method(self):" in a class) to be the assigned callback functions for fitness, generation, etc.  You can still assign flat functions (not defined in a class) as well.  I use class methods for all my pygad callbacks.

**Pull request merged**
