### PR TITLE
Adding BSD-3-Clause

### LINKED ISSUE #59: Project doesn't state a license
The README.md describes this project as 'open-source' but I can't find an actual license anywhere.
Please choose and specify the license under which this code is released as open-source, so that potential users and contributors know what they are permitted to do with it and under what conditions.

### PR DESCRIPTION
**Pull request by hyandell**
Adding a BSD-3-Clause license per email conversation with Ahmed and to resolve #59

### CODE REVIEW

**Comment by hyandell** [comment]
I opted for Copyright Ahmed Gad. An alternative is to go with "Copyright GeneticAlgorithmPython Contributors", which is basically a "Go look at the commit history" approach. Let me know if you'd prefer that.

I didn't add source headers to the files, but happy to go do that if you'd like.

**Comment by ahmedfgad** [comment]
Thanks Henri. 

I think `Copyright GeneticAlgorithmPython Contributors` is more appropriate. Let's do it.

**Comment by hyandell** [comment]
Sounds good. I've updated :)

**Comment by ahmedfgad** [comment]
Thank you.

**Pull request merged**
